


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."associazioni" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome" "text" NOT NULL,
    "descrizione" "text",
    "citta" "text",
    "email_contatto" "text",
    "sito_web" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "forma_giuridica" "text",
    "codice_fiscale" "text",
    "indirizzo_sede" "text",
    "telefono" "text",
    "profili_social" "text",
    "nome_referente" "text"
);


ALTER TABLE "public"."associazioni" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."candidature" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "posizione_id" "uuid" NOT NULL,
    "volontario_id" "uuid" NOT NULL,
    "stato" "text" DEFAULT 'in_attesa'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."candidature" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."competenze" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "is_official" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."competenze" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."imprese" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ragione_sociale" "text",
    "forma_giuridica" "text",
    "partita_iva" "text",
    "codice_fiscale" "text",
    "indirizzo_sede" "text",
    "sito_web" "text",
    "profili_social" "text",
    "nome_referente" "text",
    "settore_attivita" "text",
    "fascia_dipendenti" "text",
    "area_operativa" "text",
    "valori_cause" "text",
    "obiettivi_esg" "text",
    "tipologia_impatto" "text"
);


ALTER TABLE "public"."imprese" OWNER TO "postgres";


ALTER TABLE "public"."imprese" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."imprese_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messaggi" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "candidatura_id" "uuid" NOT NULL,
    "mittente_id" "uuid" NOT NULL,
    "testo" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."messaggi" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."posizione_competenze" (
    "posizione_id" "uuid" NOT NULL,
    "competenza_id" "uuid" NOT NULL
);


ALTER TABLE "public"."posizione_competenze" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."posizione_tags" (
    "posizione_id" "uuid" NOT NULL,
    "tag_id" "uuid" NOT NULL
);


ALTER TABLE "public"."posizione_tags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."posizioni" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "associazione_id" "uuid" NOT NULL,
    "titolo" "text" NOT NULL,
    "descrizione" "text" NOT NULL,
    "tipo" "text" NOT NULL,
    "quando" "text" NOT NULL,
    "dove" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "data_esatta" "date",
    "ora_inizio" time without time zone,
    "ora_fine" time without time zone,
    "giorni_settimana" "text"[],
    CONSTRAINT "posizioni_tipo_check" CHECK (("tipo" = ANY (ARRAY['ricorrente'::"text", 'una_tantum'::"text"])))
);


ALTER TABLE "public"."posizioni" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."volontari" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nome_completo" "text" NOT NULL,
    "bio" "text",
    "telefono" "text",
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "nome" "text",
    "cognome" "text",
    "email_contatto" "text",
    "data_nascita" "date",
    "sesso" "text",
    "citta_residenza" "text",
    "grado_istruzione" "text",
    "foto_profilo_url" "text"
);


ALTER TABLE "public"."volontari" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."volontario_competenze" (
    "volontario_id" "uuid" NOT NULL,
    "competenza_id" "uuid" NOT NULL
);


ALTER TABLE "public"."volontario_competenze" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."volontario_tags" (
    "volontario_id" "uuid" NOT NULL,
    "tag_id" "uuid" NOT NULL
);


ALTER TABLE "public"."volontario_tags" OWNER TO "postgres";


ALTER TABLE ONLY "public"."associazioni"
    ADD CONSTRAINT "associazioni_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidature"
    ADD CONSTRAINT "candidature_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidature"
    ADD CONSTRAINT "candidature_posizione_id_volontario_id_key" UNIQUE ("posizione_id", "volontario_id");



ALTER TABLE ONLY "public"."competenze"
    ADD CONSTRAINT "competenze_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."imprese"
    ADD CONSTRAINT "imprese_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messaggi"
    ADD CONSTRAINT "messaggi_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."posizione_competenze"
    ADD CONSTRAINT "posizione_competenze_pkey" PRIMARY KEY ("posizione_id", "competenza_id");



ALTER TABLE ONLY "public"."posizione_tags"
    ADD CONSTRAINT "posizione_tags_pkey" PRIMARY KEY ("posizione_id", "tag_id");



ALTER TABLE ONLY "public"."posizioni"
    ADD CONSTRAINT "posizioni_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."volontari"
    ADD CONSTRAINT "volontari_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."volontari"
    ADD CONSTRAINT "volontari_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."volontario_competenze"
    ADD CONSTRAINT "volontario_competenze_pkey" PRIMARY KEY ("volontario_id", "competenza_id");



ALTER TABLE ONLY "public"."volontario_tags"
    ADD CONSTRAINT "volontario_tags_pkey" PRIMARY KEY ("volontario_id", "tag_id");



CREATE UNIQUE INDEX "competenze_name_normalized_idx" ON "public"."competenze" USING "btree" ("lower"(TRIM(BOTH FROM "name")));



ALTER TABLE ONLY "public"."candidature"
    ADD CONSTRAINT "candidature_posizione_id_fkey" FOREIGN KEY ("posizione_id") REFERENCES "public"."posizioni"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidature"
    ADD CONSTRAINT "candidature_volontario_id_fkey" FOREIGN KEY ("volontario_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messaggi"
    ADD CONSTRAINT "messaggi_candidatura_id_fkey" FOREIGN KEY ("candidatura_id") REFERENCES "public"."candidature"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messaggi"
    ADD CONSTRAINT "messaggi_mittente_id_fkey" FOREIGN KEY ("mittente_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."posizione_competenze"
    ADD CONSTRAINT "posizione_competenze_competenza_id_fkey" FOREIGN KEY ("competenza_id") REFERENCES "public"."competenze"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."posizione_competenze"
    ADD CONSTRAINT "posizione_competenze_posizione_id_fkey" FOREIGN KEY ("posizione_id") REFERENCES "public"."posizioni"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."posizione_tags"
    ADD CONSTRAINT "posizione_tags_posizione_id_fkey" FOREIGN KEY ("posizione_id") REFERENCES "public"."posizioni"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."posizione_tags"
    ADD CONSTRAINT "posizione_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."posizioni"
    ADD CONSTRAINT "posizioni_associazione_id_fkey" FOREIGN KEY ("associazione_id") REFERENCES "public"."associazioni"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."volontario_competenze"
    ADD CONSTRAINT "volontario_competenze_competenza_id_fkey" FOREIGN KEY ("competenza_id") REFERENCES "public"."competenze"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."volontario_competenze"
    ADD CONSTRAINT "volontario_competenze_volontario_id_fkey" FOREIGN KEY ("volontario_id") REFERENCES "public"."volontari"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."volontario_tags"
    ADD CONSTRAINT "volontario_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."volontario_tags"
    ADD CONSTRAINT "volontario_tags_volontario_id_fkey" FOREIGN KEY ("volontario_id") REFERENCES "public"."volontari"("id") ON DELETE CASCADE;



CREATE POLICY "Associazione cancella competenze" ON "public"."posizione_competenze" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."posizioni"
  WHERE (("posizioni"."id" = "posizione_competenze"."posizione_id") AND ("posizioni"."associazione_id" = "auth"."uid"())))));



CREATE POLICY "Associazione inserisce competenze" ON "public"."posizione_competenze" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."posizioni"
  WHERE (("posizioni"."id" = "posizione_competenze"."posizione_id") AND ("posizioni"."associazione_id" = "auth"."uid"())))));



CREATE POLICY "I tag delle posizioni sono pubblici" ON "public"."posizione_tags" FOR SELECT USING (true);



CREATE POLICY "I tag sono leggibili da tutti" ON "public"."tags" FOR SELECT USING (true);



CREATE POLICY "I volontari possono annullare le proprie candidature" ON "public"."candidature" FOR DELETE USING (("auth"."uid"() = "volontario_id"));



CREATE POLICY "I volontari vedono le proprie candidature" ON "public"."candidature" FOR SELECT USING (("auth"."uid"() = "volontario_id"));



CREATE POLICY "Inserimento messaggi" ON "public"."messaggi" FOR INSERT WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."candidature"
  WHERE (("candidature"."id" = "messaggi"."candidatura_id") AND ("candidature"."volontario_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM ("public"."candidature" "c"
     JOIN "public"."posizioni" "p" ON (("p"."id" = "c"."posizione_id")))
  WHERE (("c"."id" = "messaggi"."candidatura_id") AND ("p"."associazione_id" = "auth"."uid"())))))));



CREATE POLICY "Le associazioni creano le proprie posizioni" ON "public"."posizioni" FOR INSERT WITH CHECK (("auth"."uid"() = "associazione_id"));



CREATE POLICY "Le associazioni eliminano le proprie posizioni" ON "public"."posizioni" FOR DELETE USING (("auth"."uid"() = "associazione_id"));



CREATE POLICY "Le associazioni possono aggiornare le candidature" ON "public"."candidature" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."posizioni"
  WHERE (("posizioni"."id" = "candidature"."posizione_id") AND ("posizioni"."associazione_id" = "auth"."uid"())))));



CREATE POLICY "Le associazioni possono cancellare i tag dei propri annunci" ON "public"."posizione_tags" FOR DELETE USING (("auth"."uid"() IN ( SELECT "posizioni"."associazione_id"
   FROM "public"."posizioni"
  WHERE ("posizioni"."id" = "posizione_tags"."posizione_id"))));



CREATE POLICY "Le associazioni possono inserire tag per i propri annunci" ON "public"."posizione_tags" FOR INSERT WITH CHECK (("auth"."uid"() IN ( SELECT "posizioni"."associazione_id"
   FROM "public"."posizioni"
  WHERE ("posizioni"."id" = "posizione_tags"."posizione_id"))));



CREATE POLICY "Le associazioni possono modificare i propri annunci" ON "public"."posizioni" FOR UPDATE USING (("auth"."uid"() = "associazione_id"));



CREATE POLICY "Le associazioni vedono le candidature ricevute" ON "public"."candidature" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."posizioni"
  WHERE (("posizioni"."id" = "candidature"."posizione_id") AND ("posizioni"."associazione_id" = "auth"."uid"())))));



CREATE POLICY "Le posizioni sono pubbliche" ON "public"."posizioni" FOR SELECT USING (true);



CREATE POLICY "Lettura messaggi" ON "public"."messaggi" FOR SELECT USING ((("auth"."role"() = 'authenticated'::"text") AND ((EXISTS ( SELECT 1
   FROM "public"."candidature"
  WHERE (("candidature"."id" = "messaggi"."candidatura_id") AND ("candidature"."volontario_id" = "auth"."uid"())))) OR (EXISTS ( SELECT 1
   FROM ("public"."candidature" "c"
     JOIN "public"."posizioni" "p" ON (("p"."id" = "c"."posizione_id")))
  WHERE (("c"."id" = "messaggi"."candidatura_id") AND ("p"."associazione_id" = "auth"."uid"())))))));



CREATE POLICY "Permetti aggiornamento profilo volontario" ON "public"."volontari" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Permetti inserimento ai loggati" ON "public"."candidature" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permetti inserimento profilo volontario" ON "public"."volontari" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Permetti inserimento tag posizioni alle associazioni" ON "public"."posizione_tags" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Permetti lettura tag posizioni a tutti gli utenti" ON "public"."posizione_tags" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Public read tags" ON "public"."volontario_tags" FOR SELECT USING (true);



CREATE POLICY "Tutti possono leggere le competenze delle posizioni" ON "public"."posizione_competenze" FOR SELECT USING (true);



CREATE POLICY "Users can delete their own tags" ON "public"."volontario_tags" FOR DELETE USING (("auth"."uid"() = "volontario_id"));



CREATE POLICY "Users can insert their own tags" ON "public"."volontario_tags" FOR INSERT WITH CHECK (("auth"."uid"() = "volontario_id"));



CREATE POLICY "Volontario cancella i suoi tag" ON "public"."volontario_tags" FOR DELETE USING (("auth"."uid"() = "volontario_id"));



CREATE POLICY "Volontario inserisce i suoi tag" ON "public"."volontario_tags" FOR INSERT WITH CHECK (("auth"."uid"() = "volontario_id"));



ALTER TABLE "public"."candidature" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."imprese" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."messaggi" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."posizione_tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."posizioni" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."volontario_tags" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."messaggi";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."associazioni" TO "anon";
GRANT ALL ON TABLE "public"."associazioni" TO "authenticated";
GRANT ALL ON TABLE "public"."associazioni" TO "service_role";



GRANT ALL ON TABLE "public"."candidature" TO "anon";
GRANT ALL ON TABLE "public"."candidature" TO "authenticated";
GRANT ALL ON TABLE "public"."candidature" TO "service_role";



GRANT ALL ON TABLE "public"."competenze" TO "anon";
GRANT ALL ON TABLE "public"."competenze" TO "authenticated";
GRANT ALL ON TABLE "public"."competenze" TO "service_role";



GRANT ALL ON TABLE "public"."imprese" TO "anon";
GRANT ALL ON TABLE "public"."imprese" TO "authenticated";
GRANT ALL ON TABLE "public"."imprese" TO "service_role";



GRANT ALL ON SEQUENCE "public"."imprese_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."imprese_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."imprese_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messaggi" TO "anon";
GRANT ALL ON TABLE "public"."messaggi" TO "authenticated";
GRANT ALL ON TABLE "public"."messaggi" TO "service_role";



GRANT ALL ON TABLE "public"."posizione_competenze" TO "anon";
GRANT ALL ON TABLE "public"."posizione_competenze" TO "authenticated";
GRANT ALL ON TABLE "public"."posizione_competenze" TO "service_role";



GRANT ALL ON TABLE "public"."posizione_tags" TO "anon";
GRANT ALL ON TABLE "public"."posizione_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."posizione_tags" TO "service_role";



GRANT ALL ON TABLE "public"."posizioni" TO "anon";
GRANT ALL ON TABLE "public"."posizioni" TO "authenticated";
GRANT ALL ON TABLE "public"."posizioni" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON TABLE "public"."volontari" TO "anon";
GRANT ALL ON TABLE "public"."volontari" TO "authenticated";
GRANT ALL ON TABLE "public"."volontari" TO "service_role";



GRANT ALL ON TABLE "public"."volontario_competenze" TO "anon";
GRANT ALL ON TABLE "public"."volontario_competenze" TO "authenticated";
GRANT ALL ON TABLE "public"."volontario_competenze" TO "service_role";



GRANT ALL ON TABLE "public"."volontario_tags" TO "anon";
GRANT ALL ON TABLE "public"."volontario_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."volontario_tags" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


